        node('agent') {
          stage 'build'
          openshiftBuild(buildConfig: 'js-playground', showBuildLogs: 'true')
          stage 'deploy'
          openshiftDeploy(deploymentConfig: 'js-playground')
        }
